CREATE TABLE FACULTY_QUESTIONS(QUESTION_ID INT, QUESTION VARCHAR(300), ANSWER VARCHAR(300), TOPIC VARCHAR(50), DIFFICULTY INT);
CREATE TABLE STUDENT_RESPONSES(Q_ID INT,  S_ID INT, ANSWERS VARCHAR(255), IS_VALID VARCHAR(1));
CREATE TABLE STUDENT_DETAILS(STD_ID INT, STD_NAME VARCHAR(300), PWD VARCHAR(300));